const CardsArray = [
  {
    link: "https://www.youtube.com/embed/sjS8vkvycmw",
    shape: "1",
    SurahNameEn: "Al-Fatiha",
    Topic: "The Opening",
    SurahNameARB: "ٱلۡفَاتِحَةِ",
    Ayahs: "7 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/Hvo4NeUxLdc",
    shape: "2",
    SurahNameEn: "Al-Baqarah",
    Topic: "The Cow",
    SurahNameARB: "البَقَرَة",
    Ayahs: "286 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/JAdx6tR1WnQ",
    shape: "3",
    SurahNameEn: "Aal-e-Imran",
    Topic: "The Family of Imran",
    SurahNameARB: "آلِ عِمْرَان",
    Ayahs: "200 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/QER4JTHn-0E",
    shape: "4",
    SurahNameEn: "An-Nisa",
    Topic: "The Women",
    SurahNameARB: "النِّسَاء",
    Ayahs: "176 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/lH-siAW6qgI",
    shape: "5",
    SurahNameEn: "Al-Ma’idah",
    Topic: "The Table Spread",
    SurahNameARB: "المَائِدَة",
    Ayahs: "120 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "6",
    SurahNameEn: "Al-An’am",
    Topic: "The Cattle",
    SurahNameARB: "الأنْعَام",
    Ayahs: "165 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "7",
    SurahNameEn: "Al-A’raf",
    Topic: "The Heights",
    SurahNameARB: "الأعْرَاف",
    Ayahs: "206 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "8",
    SurahNameEn: "Al-Anfal",
    Topic: "The Spoils of War",
    SurahNameARB: "الأنْفَال",
    Ayahs: "75 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "9",
    SurahNameEn: "At-Tawbah",
    Topic: "The Repentance",
    SurahNameARB: "التَّوبَة",
    Ayahs: "129 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "10",
    SurahNameEn: "Yunus",
    Topic: "Jonah",
    SurahNameARB: "يُونُس",
    Ayahs: "109 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "11",
    SurahNameEn: "Hud",
    Topic: "Hud",
    SurahNameARB: "هُود",
    Ayahs: "123 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "12",
    SurahNameEn: "Yusuf",
    Topic: "Joseph",
    SurahNameARB: "يُوسُف",
    Ayahs: "111 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "13",
    SurahNameEn: "Ibrahim",
    Topic: "Abraham",
    SurahNameARB: "إبْرَاهِيم",
    Ayahs: "52 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "14",
    SurahNameEn: "Al-Hijr",
    Topic: "The Rocky Tract",
    SurahNameARB: "الحِجْر",
    Ayahs: "99 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "15",
    SurahNameEn: "An-Nahl",
    Topic: "The Bee",
    SurahNameARB: "النَّحْل",
    Ayahs: "128 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "16",
    SurahNameEn: "Al-Isra",
    Topic: "The Night Journey",
    SurahNameARB: "الإسرَاء",
    Ayahs: "111 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "17",
    SurahNameEn: "Al-Isra",
    Topic: "The Night Journey",
    SurahNameARB: "الإسرَاء",
    Ayahs: "111 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "18",
    SurahNameEn: "Al-Kahf",
    Topic: "The Cave",
    SurahNameARB: "الكَهْف",
    Ayahs: "110 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "19",
    SurahNameEn: "Maryam",
    Topic: "Mary",
    SurahNameARB: "مَرْيَم",
    Ayahs: "98 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "20",
    SurahNameEn: "Ta-Ha",
    Topic: "Ta-Ha",
    SurahNameARB: "طه",
    Ayahs: "135 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "21",
    SurahNameEn: "Al-Anbiya",
    Topic: "The Prophets",
    SurahNameARB: "الأنبِياء",
    Ayahs: "112 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "22",
    SurahNameEn: "Al-Hajj",
    Topic: "The Pilgrimage",
    SurahNameARB: "الحَج",
    Ayahs: "78 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "23",
    SurahNameEn: "Al-Mu’minun",
    Topic: "The Believers",
    SurahNameARB: "المُؤْمِنُون",
    Ayahs: "118 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "24",
    SurahNameEn: "An-Nur",
    Topic: "The Light",
    SurahNameARB: "النُّور",
    Ayahs: "64 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "25",
    SurahNameEn: "Al-Furqan",
    Topic: "The Criterion",
    SurahNameARB: "الفرْقَان",
    Ayahs: "77 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "26",
    SurahNameEn: "Ash-Shu’ara",
    Topic: "The Poets",
    SurahNameARB: "الشُّعَرَاء",
    Ayahs: "227 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "27",
    SurahNameEn: "An-Naml",
    Topic: "The Ant",
    SurahNameARB: "النَّمل",
    Ayahs: "93 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "28",
    SurahNameEn: "Al-Qasas",
    Topic: "The Stories",
    SurahNameARB: "القَصَص",
    Ayahs: "88 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "29",
    SurahNameEn: "Al-Ankabut",
    Topic: "The Spider",
    SurahNameARB: "العنكبوت",
    Ayahs: "69 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XYZ", // Replace with the actual link
    shape: "30",
    SurahNameEn: "Ar-Rum",
    Topic: "The Romans",
    SurahNameARB: "الرُّوم",
    Ayahs: "60 Ayahs",
  },



    {
    link: "https://www.youtube.com/embed/Kb0GuzuTxys",
    shape: "31",
    SurahNameEn: "Luqman",
    Topic: "Luqman",
    SurahNameARB: "لقمان",
    Ayahs: "34 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/BXQNWTH5b6g",
    shape: "32",
    SurahNameEn: "As-Sajdah",
    Topic: "The Prostration",
    SurahNameARB: "السجدة",
    Ayahs: "30 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/fyTTBm40EsI",
    shape: "33",
    SurahNameEn: "Al-Ahzab",
    Topic: "The Confederates",
    SurahNameARB: "الأحزاب",
    Ayahs: "73 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/fO6-swedJ1Y",
    shape: "34",
    SurahNameEn: "Saba",
    Topic: "Sheba",
    SurahNameARB: "سبأ",
    Ayahs: "54 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/oVP46R8tRnE",
    shape: "35",
    SurahNameEn: "Fatir",
    Topic: "The Originator",
    SurahNameARB: "فاطر",
    Ayahs: "45 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/MA9vsGaH3U0",
    shape: "36",
    SurahNameEn: "Ya-Sin",
    Topic: "Ya-Sin",
    SurahNameARB: "يس",
    Ayahs: "83 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/tOafZpE1KvE",
    shape: "37",
    SurahNameEn: "As-Saffat",
    Topic: "Those who set the Ranks",
    SurahNameARB: "الصافات",
    Ayahs: "182 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/MQbWkv8E4NQ",
    shape: "38",
    SurahNameEn: "Sad",
    Topic: "The Letter Sad",
    SurahNameARB: "ص",
    Ayahs: "88 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/583u5D3p4hA",
    shape: "39",
    SurahNameEn: "Az-Zumar",
    Topic: "The Groups",
    SurahNameARB: "الزمر",
    Ayahs: "75 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/aoJzNFZD_fA",
    shape: "40",
    SurahNameEn: "Ghafir",
    Topic: "The Forgiver",
    SurahNameARB: "غافر",
    Ayahs: "85 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/atfTeTESraU",
    shape: "41",
    SurahNameEn: "Fussilat",
    Topic: "Explained in Detail",
    SurahNameARB: "فصلت",
    Ayahs: "54 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/8OKv3US9MuQ",
    shape: "42",
    SurahNameEn: "Ash-Shura",
    Topic: "The Consultation",
    SurahNameARB: "الشورى",
    Ayahs: "53 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/3m-6L-WLcE0",
    shape: "43",
    SurahNameEn: "Az-Zukhruf",
    Topic: "The Gold Adornments",
    SurahNameARB: "الزخرف",
    Ayahs: "89 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/Y2Tx95Ub974",
    shape: "44",
    SurahNameEn: "Ad-Dukhan",
    Topic: "The Smoke",
    SurahNameARB: "الدخان",
    Ayahs: "59 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/xa-XjV0kfQI",
    shape: "45",
    SurahNameEn: "Al-Jathiya",
    Topic: "The Kneeling",
    SurahNameARB: "الجاثية",
    Ayahs: "37 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/D7JHBkGMCl8",
    shape: "46",
    SurahNameEn: "Al-Ahqaf",
    Topic: "The Wind-Curved Sandhills",
    SurahNameARB: "الأحقاف",
    Ayahs: "35 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/xm-n_LO-slY",
    shape: "47",
    SurahNameEn: "Muhammad",
    Topic: "Muhammad",
    SurahNameARB: "محمد",
    Ayahs: "38 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/rYeTZbOTNyg",
    shape: "48",
    SurahNameEn: "Al-Fath",
    Topic: "The Victory",
    SurahNameARB: "الفتح",
    Ayahs: "29 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/yY-hD9nj9-k",
    shape: "49",
    SurahNameEn: "Al-Hujurat",
    Topic: "The Rooms",
    SurahNameARB: "الحجرات",
    Ayahs: "18 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/RFow2bQ51-8",
    shape: "50",
    SurahNameEn: "Qaf",
    Topic: "The Letter Qaf",
    SurahNameARB: "ق",
    Ayahs: "45 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/TWXxn2gJMw4",
    shape: "51",
    SurahNameEn: "Al-Asr",
    Topic: "The Time",
    SurahNameARB: "العَصْر",
    Ayahs: "3 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/4gr_pUrJ8SA",
    shape: "52",
    SurahNameEn: "Al-Humazah",
    Topic: "The Scorning",
    SurahNameARB: "الهمَزَة",
    Ayahs: "9 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/z9yzYp3kMuo",
    shape: "53",
    SurahNameEn: "Al-Fil",
    Topic: "The Elephant",
    SurahNameARB: "الفِيل",
    Ayahs: "5 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/-BOPRK-5Tag",
    shape: "54",
    SurahNameEn: "Quraish",
    Topic: "Quraish",
    SurahNameARB: "قُرَيْش",
    Ayahs: "4 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/o4snn9Kxvr8",
    shape: "55",
    SurahNameEn: "Al-Ma’un",
    Topic: "The Small Kindnesses",
    SurahNameARB: "المَاعُون",
    Ayahs: "7 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/0OklPDe2AVQ",
    shape: "56",
    SurahNameEn: "Al-Waqi'ah",
    Topic: "The Inevitable",
    SurahNameARB: "الواقعة",
    Ayahs: "96 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/V7a8GOaE-fU",
    shape: "57",
    SurahNameEn: "Al-Kafirun",
    Topic: "The Disbelievers",
    SurahNameARB: "الكَافِرُون",
    Ayahs: "6 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/08kKYHMf1Qw",
    shape: "58",
    SurahNameEn: "An-Nasr",
    Topic: "The Divine Support",
    SurahNameARB: "النَّصْر",
    Ayahs: "3 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/fZc5B-T55zU",
    shape: "59",
    SurahNameEn: "Al-Masad",
    Topic: "The Palm Fiber",
    SurahNameARB: "المَسَد",
    Ayahs: "5 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/Ev2F3QmAM_8",
    shape: "60",
    SurahNameEn: "Al-Ikhlas",
    Topic: "The Sincerity",
    SurahNameARB: "الإخْلَاص",
    Ayahs: "4 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/Sb-eTTMZogQ",
    shape: "61",
    SurahNameEn: "Al-Falaq",
    Topic: "The Daybreak",
    SurahNameARB: "الفَلَق",
    Ayahs: "5 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/jx8kWsX2Wj4",
    shape: "62",
    SurahNameEn: "An-Nas",
    Topic: "Mankind",
    SurahNameARB: "النَّاس",
    Ayahs: "6 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/85OykieQ92U",
    shape: "63",
    SurahNameEn: "Al-‘Alaq",
    Topic: "The Clot",
    SurahNameARB: "الْعَلَق",
    Ayahs: "19 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/omtp5navQdI",
    shape: "64",
    SurahNameEn: "Al-Qadr",
    Topic: "The Power",
    SurahNameARB: "الْقَدَر",
    Ayahs: "5 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/3qfknrCiU20",
    shape: "65",
    SurahNameEn: "Al-Mujadila",
    Topic: "The Pleading Woman",
    SurahNameARB: "المُجَادِلَة",
    Ayahs: "22 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/pwhcl4kD9FY",
    shape: "66",
    SurahNameEn: "Al-Mumtahina",
    Topic: "She That Is to be Examined",
    SurahNameARB: "المُمَتَّنَة",
    Ayahs: "13 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/LnAVrcrbk2A",
    shape: "67",
    SurahNameEn: "Al-Mulk",
    Topic: "The Sovereignty",
    SurahNameARB: "المُلْك",
    Ayahs: "30 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/DfOAOwGxH1c",
    shape: "68",
    SurahNameEn: "Al-Qalam",
    Topic: "The Pen",
    SurahNameARB: "القَلَم",
    Ayahs: "52 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/TEpKHsVWkbI",
    shape: "69",
    SurahNameEn: "Al-Haqqah",
    Topic: "The Inevitable",
    SurahNameARB: "الحَاقَّة",
    Ayahs: "52 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/r8XvAGjbjKw",
    shape: "70",
    SurahNameEn: "Al-Ma’arij",
    Topic: "The Ascending Stairways",
    SurahNameARB: "المَعَارِج",
    Ayahs: "44 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/d4-fP_dekW8",
    shape: "71",
    SurahNameEn: "Nuh",
    Topic: "Noah",
    SurahNameARB: "نُوح",
    Ayahs: "28 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/Ef3oDvtYMz8",
    shape: "72",
    SurahNameEn: "Al-Jinn",
    Topic: "The Jinn",
    SurahNameARB: "الجِن",
    Ayahs: "28 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/x8JaJTGd4TQ",
    shape: "73",
    SurahNameEn: "Al-Muzzammil",
    Topic: "The Enshrouded One",
    SurahNameARB: "المُزَّمِّل",
    Ayahs: "20 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/44jkgZ-zobY",
    shape: "74",
    SurahNameEn: "Al-Muddathir",
    Topic: "The Cloaked One",
    SurahNameARB: "المُدَّثِّر",
    Ayahs: "56 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/wmXTkzl-RmI",
    shape: "75",
    SurahNameEn: "Al-Qiyamah",
    Topic: "The Resurrection",
    SurahNameARB: "الْقِيَامَة",
    Ayahs: "40 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/RC7VYGI4tCI",
    shape: "76",
    SurahNameEn: "Al-Insan",
    Topic: "Man",
    SurahNameARB: "الإنسان",
    Ayahs: "31 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/KZZjLT-GudI",
    shape: "77",
    SurahNameEn: "Al-Mursalat",
    Topic: "The Emissaries",
    SurahNameARB: "المُرْسَلَات",
    Ayahs: "50 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/KCCKfnYSM7Q",
    shape: "78",
    SurahNameEn: "An-Naba",
    Topic: "The Tidings",
    SurahNameARB: "النبَأ",
    Ayahs: "40 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/WqrHnDz8MOY",
    shape: "79",
    SurahNameEn: "An-Nazi’at",
    Topic: "Those Who Drag Forth",
    SurahNameARB: "النَّازِعَات",
    Ayahs: "46 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/0O25KB1lXLA",
    shape: "80",
    SurahNameEn: "Abasa",
    Topic: "He Frowned",
    SurahNameARB: "عبس",
    Ayahs: "42 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/KBYGHr4IsQY",
    shape: "81",
    SurahNameEn: "At-Takwir",
    Topic: "The Overthrowing",
    SurahNameARB: "التَّكْوِير",
    Ayahs: "29 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XNn_elVu4pI",
    shape: "82",
    SurahNameEn: "Al-Infitar",
    Topic: "The Cleaving",
    SurahNameARB: "الانفِطار",
    Ayahs: "19 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/at5VTAwB5XI",
    shape: "83",
    SurahNameEn: "Al-Mutaffifin",
    Topic: "Defrauding",
    SurahNameARB: "المُطَفِّفِينَ",
    Ayahs: "36 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/OWbbAoRsj_k",
    shape: "84",
    SurahNameEn: "Al-Inshiqaq",
    Topic: "The Splitting Open",
    SurahNameARB: "الانشِقَاق",
    Ayahs: "25 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/sCM166IoT3I",
    shape: "85",
    SurahNameEn: "Al-Buruj",
    Topic: "The Mansions of the Stars",
    SurahNameARB: "البُروج",
    Ayahs: "22 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/RPgYKfyzhKI",
    shape: "86",
    SurahNameEn: "At-Tariq",
    Topic: "The Morning Star",
    SurahNameARB: "الطَّارِق",
    Ayahs: "17 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/kqlODaDH4Zc",
    shape: "87",
    SurahNameEn: "Al-A’la",
    Topic: "The Most High",
    SurahNameARB: "الأعلى",
    Ayahs: "19 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/mHg6kB2mAww",
    shape: "88",
    SurahNameEn: "Al-Ghashiya",
    Topic: "The Overwhelming",
    SurahNameARB: "الغاشية",
    Ayahs: "26 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/QU5tIoKjVjI",
    shape: "89",
    SurahNameEn: "Al-Fajr",
    Topic: "The Dawn",
    SurahNameARB: "الفجر",
    Ayahs: "30 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/zvT1ofZHRVw",
    shape: "90",
    SurahNameEn: "Al-Balad",
    Topic: "The City",
    SurahNameARB: "البلد",
    Ayahs: "20 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/2Ikgj0XTWvA",
    shape: "91",
    SurahNameEn: "Ash-Shams",
    Topic: "The Sun",
    SurahNameARB: "الشَّمس",
    Ayahs: "15 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/Wz7pA_AyLnY",
    shape: "92",
    SurahNameEn: "Al-Lail",
    Topic: "The Night",
    SurahNameARB: "الليل",
    Ayahs: "21 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/-GtTajxae8g",
    shape: "93",
    SurahNameEn: "Ad-Duha",
    Topic: "The Morning Hours",
    SurahNameARB: "الضحى",
    Ayahs: "11 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/PfG3uMOUtLo",
    shape: "94",
    SurahNameEn: "Ash-Sharh",
    Topic: "The Relief",
    SurahNameARB: "الشرح",
    Ayahs: "8 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/iOS16WRLu4M",
    shape: "95",
    SurahNameEn: "At-Tin",
    Topic: "The Fig",
    SurahNameARB: "التين",
    Ayahs: "8 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/AM_VULpFcNo",
    shape: "96",
    SurahNameEn: "Al-Alaq",
    Topic: "The Clot",
    SurahNameARB: "العلق",
    Ayahs: "19 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/zpPaOREAkqw",
    shape: "97",
    SurahNameEn: "Al-Qadr",
    Topic: "The Power",
    SurahNameARB: "القدر",
    Ayahs: "5 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/1eji_5tZb-c",
    shape: "98",
    SurahNameEn: "Al-Bayyina",
    Topic: "The Clear Proof",
    SurahNameARB: "البيِّنة",
    Ayahs: "8 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/rqK41yKCKiM",
    shape: "99",
    SurahNameEn: "Az-Zalzalah",
    Topic: "The Earthquake",
    SurahNameARB: "الزلزلة",
    Ayahs: "8 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/2J8TN346ff8",
    shape: "100",
    SurahNameEn: "Al-Adiyat",
    Topic: "The Courser",
    SurahNameARB: "العديات",
    Ayahs: "11 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/vb9ChJaf7cM",
    shape: "101",
    SurahNameEn: "Al-Qari’ah",
    Topic: "The Striking Hour",
    SurahNameARB: "القارعة",
    Ayahs: "11 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/XCUIVzfW49c",
    shape: "102",
    SurahNameEn: "At-Takathur",
    Topic: "The Rivalry in Worldly Increase",
    SurahNameARB: "التكاثر",
    Ayahs: "8 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/jUf3hhYPpPI",
    shape: "103",
    SurahNameEn: "Al-Asr",
    Topic: "The Declining Day",
    SurahNameARB: "العصر",
    Ayahs: "3 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/OkHl5-fFE00",
    shape: "104",
    SurahNameEn: "Al-Humazah",
    Topic: "The Slanderer",
    SurahNameARB: "الهمزة",
    Ayahs: "9 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/N-CvkMS5YyU",
    shape: "105",
    SurahNameEn: "Al-Fil",
    Topic: "The Elephant",
    SurahNameARB: "الفيل",
    Ayahs: "5 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/x_XZl1MYAoI",
    shape: "106",
    SurahNameEn: "Quraish",
    Topic: "Quraish",
    SurahNameARB: "قريش",
    Ayahs: "4 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/JB7zfhJ-TLU",
    shape: "107",
    SurahNameEn: "Al-Ma’un",
    Topic: "The Small Kindnesses",
    SurahNameARB: "الماعون",
    Ayahs: "7 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/U6mvs4ifVzY",
    shape: "108",
    SurahNameEn: "Al-Kawthar",
    Topic: "The Abundance",
    SurahNameARB: "الكَوثر",
    Ayahs: "3 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/6nHtvH0GXKw",
    shape: "109",
    SurahNameEn: "Al-Kafirun",
    Topic: "The Disbelievers",
    SurahNameARB: "الكافرون",
    Ayahs: "6 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/Ot-1RsOwOgU",
    shape: "110",
    SurahNameEn: "An-Nasr",
    Topic: "The Divine Support",
    SurahNameARB: "النصر",
    Ayahs: "3 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/bkr3QoewGKw",
    shape: "111",
    SurahNameEn: "Al-Masad",
    Topic: "The Palm Fiber",
    SurahNameARB: "المسد",
    Ayahs: "5 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/b9YEdjef2oA",
    shape: "112",
    SurahNameEn: "Al-Ikhlas",
    Topic: "The Purity",
    SurahNameARB: "الإخلاص",
    Ayahs: "4 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/pFuWbddyiuo",
    shape: "113",
    SurahNameEn: "Al-Falaq",
    Topic: "The Daybreak",
    SurahNameARB: "الفلق",
    Ayahs: "5 Ayahs",
  },
  {
    link: "https://www.youtube.com/embed/-GtTajxae8g",
    shape: "114",
    SurahNameEn: "An-Nas",
    Topic: "The People",
    SurahNameARB: "الناس",
    Ayahs: "6 Ayahs",
  }

];

  
export default CardsArray